"""Initial migration

Revision ID: 47a8b0768b48
Revises: 
Create Date: 2023-10-12 14:13:10.641580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47a8b0768b48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_shows')
    op.drop_table('tv_show_genres')
    op.drop_table('tv_genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_genres',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tv_show_genres',
    sa.Column('show_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('genre_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['tv_genres.id'], name='tv_show_genres_ibfk_2'),
    sa.ForeignKeyConstraint(['show_id'], ['tv_shows.id'], name='tv_show_genres_ibfk_1'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tv_shows',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
